### ISSUE TITLE
Potential codegen bug

### ISSUE THREAD

**Issue by Y-Less** [PatrickGTR/MySQL-Prepared-Statements#1]
I don't know if you've tried this on the old compiler, or even want to, but there's a bug where `#emit` directly after `}` gets contained in the braces instead of after them:

https://github.com/PatrickGTR/MySQL-Prepared-Statements/blob/b872b4b46e1a42834d1130c6ba892e658eb4ceb5/mysql_prepared.inc#L553-L558

The way to fix it is to place `{}` between:

```pawn
				}

				{}

				// format(output[], len, const format[], {Float,_}:...)
				#emit PUSH.S address //push address of variable address
```

**Comment by Y-Less** [comment]
Just saw this:

https://github.com/PatrickGTR/MySQL-Prepared-Statements/blob/b872b4b46e1a42834d1130c6ba892e658eb4ceb5/mysql_prepared.inc#L362

Possibly the same issue.  That line fixes it just as `{}` would - literally any high-level statement fully ends the preceding brace.

**Comment by PatrickGTR** [comment]
I'll sort it out as soon as I finish my Fortnite tournament (8 PM). If you can pull a request it would be greatly appreciated. Thanks for pointing it out!
