### ISSUE TITLE
Unused assignment

### ISSUE THREAD

**Issue by Daniel-Cortez** [PatrickGTR/MySQL-Prepared-Statements#4]
The following code in function `stmt_close()` looks suspicious:
https://github.com/PatrickGTR/MySQL-Prepared-Statements/blob/3c781e5efd172b20697f997cfd2653c66edd1380/mysql_prepared.inc#L123-L127
The assignment `statement = INVALID_STATEMENT;` seems to be unused (`statement` is neither passed by reference nor a global variable). Was this intended?

**Comment by PatrickGTR** [comment]
Hello, sorry for a really long late reply. I just seen this.

iirc it is used to free up a statements. statements that requires one time use only, but another alternative is to bump up the value of ``MAX_STATEMENTS``

**Comment by Daniel-Cortez** [comment]
> iirc it is used to free up a statements. statements that requires one time use only

I didn't mean the whole function, I only meant the line `statement = INVALID_STATEMENT;` which seems to be redundant code, as the value assigned to `statement` on that line is unused upon return.
I discovered it with [this new feature](https://github.com/pawn-lang/compiler/pull/480) (currently pending approval).

**Comment by PatrickGTR** [comment]
After reading, it makes sense! Thanks for bringing this up.

#4 #
